name: docking
description: Flutter layout for placing widgets in docking areas and arrange them into split and tabbed views.
version: 1.17.0
homepage: https://caduandrade.github.io/docking_flutter/
repository: https://github.com/caduandrade/docking_flutter

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  tabbed_view: '>=1.19.1 <1.20.0'
    #path: ../tabbed_view/
  multi_split_view: '>=3.6.1-rc.2 <3.7.0'
    #path: ../multi_split_view/

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true